name: Generate POT file
on:
    push:
        branches:
            - main

jobs:
    WP_Generate_POT_File:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: WordPress .pot File Generator
              uses: iamdharmesh/action-wordpress-pot-generator@main
              with:
                  destination_path: "./languages"
                  slug: "xenial"
                  text_domain: "xenial"
              env:
                  GITHUB_TOKEN: ${{ secrets.WPPOT_TOKEN }}
